# Generated by Django 2.0 on 2018-07-22 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaiZan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContentItems',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('posttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('postposition', models.CharField(default='', max_length=90)),
                ('content', models.TextField()),
                ('picture', models.ImageField(default=None, upload_to='Content_img')),
                ('cai', models.IntegerField(default=0)),
                ('isshowname', models.BooleanField(default=True)),
                ('uid', models.ForeignKey(on_delete=False, related_name='auth_user_contentItems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='caizan',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentitems_caizan', to='blog.ContentItems'),
        ),
        migrations.AddField(
            model_name='caizan',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user_caizan', to=settings.AUTH_USER_MODEL),
        ),
    ]
