# Generated by Django 2.0 on 2018-07-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentItems',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('posttime', models.DateTimeField(auto_now_add=True)),
                ('postposition', models.CharField(max_length=90)),
                ('content', models.TextField()),
                ('picture', models.ImageField(default=None, upload_to='Content_img')),
                ('cai', models.IntegerField(default=0)),
                ('isshowname', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('sex', models.BooleanField(default=False)),
                ('phonenumber', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('heading', models.ImageField(default='img/4.jpg', upload_to='img')),
                ('sex', models.BooleanField(default=False)),
                ('phonenumber', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('isactivity', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='contentitems',
            name='userid',
            field=models.ForeignKey(on_delete=False, related_name='users_contentItems', to='blog.Users'),
        ),
    ]
