# Generated by Django 2.0 on 2018-07-18 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItems',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('posttime', models.DateTimeField(auto_now_add=True)),
                ('postposition', models.CharField(default='', max_length=90)),
                ('content', models.TextField()),
                ('picture', models.ImageField(default=None, upload_to='Content_img')),
                ('cai', models.IntegerField(default=0)),
                ('isshowname', models.BooleanField(default=True)),
                ('uid', models.ForeignKey(on_delete=False, related_name='auth_user_contentItems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
