# Generated by Django 2.0 on 2018-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('sex', models.BooleanField(default=False)),
                ('phonenumber', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=64)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
