# Generated by Django 2.0 on 2018-07-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180710_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
